[package]
name = "arycal-common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
tqdm = {git = "https://github.com/singjc/tqdm.git", branch = "add/update_desc"}