[package]
name = "arycal-common"
version = "0.1.4"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
tqdm = {git = "https://github.com/singjc/tqdm.git", branch = "add/update_desc"}