[package]
name = "arycal-common"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
ordered-float = "5.0.0"
savgol-rs = "0.1.0"
deepsize = "0.2.0"