name: Docker Image CI

on:
  workflow_dispatch:  # Allow manual triggering
  release:
    types: [published, edited]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: singjc/arycal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Get Cargo toolchain (pinned)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.85.0   # <-- Pin to pre-1.81 to avoid anymap UB issue
        target: x86_64-unknown-linux-gnu
        override: true
    
    - name: Build arycal
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-unknown-linux-gnu --bin arycal

    - name: Build arycal-gui
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-unknown-linux-gnu --bin arycal-gui
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Push the Docker image to the GHCR
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
