name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - name: arycal-x86_64-unknown-linux-musl
            bin: arycal
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest

          - name: arycal-x86_64-unknown-linux-musl-mpi
            bin: arycal
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            features: mpi

          - name: arycal-gui-x86_64-ubuntu_22_04-linux-gnu
            bin: arycal-gui
            target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04  # Ensures older glibc for compatibility

          - name: arycal-x86_64-apple-darwin
            bin: arycal
            target: x86_64-apple-darwin
            os: macos-latest

          - name: arycal-gui-x86_64-apple-darwin
            bin: arycal-gui
            target: x86_64-apple-darwin
            os: macos-latest

          - name: arycal-x86_64-pc-windows-msvc
            bin: arycal
            target: x86_64-pc-windows-msvc
            os: windows-latest

          - name: arycal-gui-x86_64-pc-windows-msvc
            bin: arycal-gui
            target: x86_64-pc-windows-msvc
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install musl-tools (for Linux musl builds)
        if: contains(matrix.target, 'musl')
        run: sudo apt-get install -y musl-tools

      - name: Install Dependencies (for Arycal-GUI on Linux)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: sudo apt-get install -y libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libegl1-mesa libgtk-3-dev

      - name: Build Arycal (Regular)
        if: matrix.name == 'arycal-linux-musl'
        run: cargo build --release --target=${{ matrix.target }}

      - name: Build Arycal (with MPI)
        if: matrix.name == 'arycal-linux-musl-mpi'
        run: cargo build --release --target=${{ matrix.target }} --features mpi

      - name: Build Arycal-GUI
        if: matrix.name == 'arycal-gui-linux-gnu'
        run: cargo build --release --target=${{ matrix.target }}

      - name: Upload Release Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ matrix.bin }}
          archive: ${{ matrix.bin }}-{{ $tag }}-${{ matrix.name }}
          target: ${{ matrix.target }}
          include: LICENSE,README.md
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
          rename: ${{ matrix.name }}
